# Generated by Django 6.0.3 on 2026-03-15 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
