# Generated by Django 6.0.3 on 2026-03-15 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_student_batch_remove_student_user'),
        ('enrollments', '0002_alter_enrollment_student'),
        ('results', '0002_alter_semesterresult_student'),
        ('transcripts', '0002_alter_transcript_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
