# Generated by Django 6.0.3 on 2026-03-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EXAM_OFFICER', 'Examination Officer'), ('DEPT_CONTROLLER', 'Department Exam Controller'), ('INTERNAL_EXAM_CONTROLLER', 'Department Internal Exam Controller'), ('STUDENT', 'Student')], max_length=30),
        ),
        migrations.CreateModel(
            name='RoleModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('EXAM_OFFICER', 'Examination Officer'), ('DEPT_CONTROLLER', 'Department Exam Controller'), ('INTERNAL_EXAM_CONTROLLER', 'Department Internal Exam Controller'), ('STUDENT', 'Student')], max_length=30)),
                ('module', models.CharField(choices=[('DEPARTMENTS', 'Departments'), ('BATCHES', 'Batches'), ('SEMESTERS', 'Semesters'), ('SESSIONS', 'Sessions'), ('COURSES', 'Courses'), ('COURSE_OFFERINGS', 'Course Offerings'), ('ENROLLMENTS', 'Enrollments'), ('EXAMS', 'Exams/Marks'), ('RESULTS', 'Results'), ('TRANSCRIPTS', 'Transcripts'), ('STUDENTS', 'Students')], max_length=30)),
                ('can_create', models.BooleanField(default=True)),
                ('can_read', models.BooleanField(default=True)),
                ('can_update', models.BooleanField(default=True)),
                ('can_delete', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('role', 'module')},
            },
        ),
    ]
