# Generated by Django 6.0.3 on 2026-03-15 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
        ('transcripts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='admission.student'),
        ),
    ]
