# Generated by Django 6.0.3 on 2026-03-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_alter_enrollment_student'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_cgpa_dropout', models.FloatField(default=1.0)),
                ('min_cgpa_probation', models.FloatField(default=2.0)),
                ('max_probations_allowed', models.IntegerField(default=2)),
                ('failed_marks_threshold', models.FloatField(default=50.0)),
                ('improvement_min', models.FloatField(default=50.0)),
                ('improvement_max', models.FloatField(default=62.0)),
                ('no_drop_after_semester', models.IntegerField(default=1)),
                ('can_drop', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamSplitConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessional_max', models.IntegerField(default=30)),
                ('midterm_max', models.IntegerField(default=30)),
                ('terminal_max', models.IntegerField(default=40)),
            ],
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_percentage', models.FloatField()),
                ('max_percentage', models.FloatField()),
                ('grade', models.CharField(max_length=5)),
                ('grade_point', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-min_percentage'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='marks',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='marks',
            name='exam',
        ),
        migrations.AddField(
            model_name='marks',
            name='exam_type',
            field=models.CharField(choices=[('SESSIONAL', 'Sessional'), ('MIDTERM', 'Midterm'), ('TERMINAL', 'Terminal')], default='TERMINAL', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='marks',
            unique_together={('enrollment', 'exam_type')},
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
