# Generated by Django 6.0.3 on 2026-03-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_department_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='batches',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='academics.batch'),
        ),
        migrations.AddField(
            model_name='session',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='academics.department'),
        ),
    ]
